force_train: False
checkpoint: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/checkpoints/6b63831df3c54a7aae1e902ca7ad3c72.ckpt
checkpoint_train_dir: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/crops/train
checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/classification/checkpoints
train_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/train
val_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/val
fast_dev_run: True
max_epochs: 10
lr: 0.00001
batch_size: 16
workers: 5
