force_train: False
checkpoint: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/checkpoints/bdcd2b1d9d6c44c0aef87d5e73b9e154.ckpt
checkpoint_train_dir: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/crops/train
checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/classification/checkpoints
train_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/train
val_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/val
fast_dev_run: True
max_epochs: 10
lr: 0.00001
batch_size: 72
workers: 5
