force_train: False
checkpoint: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/checkpoints/b6a9a27382c645fc9755eb5d7faf9ed3.ckpt
checkpoint_train_dir: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/crops/train
checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/classification/checkpoints
train_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/train
val_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/val
fast_dev_run: True
max_epochs: 10
lr: 0.00001
batch_size: 72
workers: 5
