backend: hierarchical
force_train: False
# Optional: explicitly set checkpoint path; if empty we auto-discover under tamu_hcast/
checkpoint: 
# Batch size for classifying crops after detection
batch_size: 64
workers: 4
# Optional label mapping override: path to CSV with one column 'label'
label_list: 

