name: Run Tests

on: [push, pull_request]

jobs:
  test:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install package
      run: uv sync --all-extras --dev

    - name: Run pytest
      run: uv run pytest -v
